### ISSUE TITLE
🐛 Çalışmayan linkler sorunu

### ISSUE THREAD

**Issue by asmaamirkhan** [YEmreAk/YLearn#3]
Projenin [bu](https://learn.yemreak.com/web-programlama#analizler) ve [bu](https://learn.yemreak.com/veri-bilimi#veri-bilimi-baslangic-kiti) kısımları çalışmayan linkler içermekte ⚠ (404 hatası 🚧)

**Comment by yedhrab** [comment]
Sen düzeltebilir misin

**Comment by yemreak** [comment]
Düzeltildi, teşekkürler :)
